// <auto-generated />
using System;
using JM_Examen_P1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JM_Examen_P1.Migrations
{
    [DbContext(typeof(JM_Examen_P1Context))]
    partial class JM_Examen_P1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JM_Examen_P1.Models.Montero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("JM_Estudiante")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JM_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("JM_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("JM_Nota")
                        .HasColumnType("float");

                    b.Property<int>("JM_SemestreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Montero");
                });
#pragma warning restore 612, 618
        }
    }
}
